#!/bin/bash
# Adapted from <https://bugzilla.redhat.com/show_bug.cgi?id=116961>

_make_completion() { 
    if [ -f Makefile ]; then
        COMPREPLY=($(grep "^[[:alnum:]]\+:" Makefile | sed 's/:.*$//'))
    fi
}
complete -o default -o nospace -F _make_completion make

