#!/bin/bash
# Git info for PS1

# Display an asterisk if the branch is dirty
function git_dirty_status {
    git diff --quiet || echo '-'
}

# Display a plus sign if the branch is ahead
function git_push_status {
   [[ $(git status | grep 'Your branch is ahead') ]] && echo '+';
}

# Displays: <branch><dirty|push>
function git_prompt {
    # bail if no git repo
    git branch &> /dev/null || return 1
    p=$(__git_ps1 "%s")
    if [ $(git_dirty_status) ]; then
        s=$(git_dirty_status)
    else
        s=$(git_push_status)
    fi
    echo " ($p $s)"
}

