#!/bin/bash
# PS1 prompting

# Git: Display an asterisk if the branch is dirty
function git_dirty_status {
    git diff --quiet || echo '-'
}

# Git: Display a plus sign if the branch is ahead
function git_push_status {
   [[ $(git status | grep 'Your branch is ahead') ]] && echo '+';
}

# Git: Displays: <branch><dirty|push>
function git_prompt {
    # bail if no git repo
    git branch &> /dev/null || return 1
    p=$(__git_ps1 "%s")
    if [ $(git_dirty_status) ]; then
        s=$(git_dirty_status)
    else
        s=$(git_push_status)
    fi
    echo " ($p $s)"
}

# Display "#" for root/sudo and "$" for users
function user_sigil {
    if [ $UID -eq 0 ]; then
        echo '#'
    else
        echo '$'
    fi
}

# Cobble the above functions together for PS1 usage; PS1 set in .bashrc
function show_prompt {
    # {title=user@host} {cwd} {git_prompt}
    echo "\[\e]2;\u@\h\a\w\[\e[1;31m\]\$(git_prompt) \$\[\e[0m\] "
}

