#!/bin/bash
# PS1 prompting

# Git: Used by git-completion
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

# Git: Display a caret if the branch is ahead
function git_push_status {
   [[ $(git status | grep 'Your branch is ahead') ]] && echo '^';
}

# Git: Displays: <branch><dirty|push>
function git_prompt {
    # bail if no git repo
    git branch &> /dev/null || return 1
    p=$(__git_ps1 "%s")$(git_push_status)
    echo " ($p)"
}

# Cobble the above functions together for PS1 usage; PS1 set in .bashrc
function show_prompt {
    # {title=user@host} {cwd} {git_prompt} {sigil}
    echo "\[\033]0;\u@\h\007\]\w\[\e[1;31m\]\$(git_prompt) \\$\[\e[0m\] "
}

